version: '3.8'

services:
  django:
    build:
      context: ./overratedproject/overratedproject
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./overratedproject/:/code
    ports:
      - 8000:8000

  client:
    build:
      context: ./overratedproject/frontend
    volumes:
      - ./overratedproject/frontend/:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    depends_on:
      - django
