# Generated by Django 4.1.7 on 2023-06-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overratedproject", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destinationcard",
            name="location",
            field=models.CharField(max_length=100),
        ),
    ]
