# Generated by Django 4.1.7 on 2023-06-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("overratedproject", "0002_alter_destinationcard_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewcard",
            name="review",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
